export const Skills = [
  { title: "HTML"},
  { title: "CSS"},
  { title: "Js"},
  { title: "NodeJs"},
  { title: "ReactJs"},
  { title: "AngularJs"},
  { title: "MySQL"},
  { title: "MongoDB"},
  { title: "Python"},
  { title: "Machine Learning"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"},
  { title: "other"}
]
  
export const Users = [
  {
    id: 0,
    name: "Jessy Lane",
    skill: [
      { title: "NodeJs", level: 3 } ,
      { title: "ReactJs", level: 2 },
      { title: "Machine Learning", level: 2} ,
      { title: "AngularJs", level: 1 },
      { title: "MongoDB", level: 1 },
      { title: "Python", level: 1 }
    ]
  },
  {
    id: 1,
    name: "James Anderson",
    skill: [
      { title: "NodeJs", level: 3 } ,
      { title: "ReactJs", level: 2 },
    ]
  },
  {
    id: 2,
    name: "Doris Coleman",
    skill: [
      { title: "NodeJs", level: 3 } ,
      { title: "Python", level: 1 }
    ]
  },
  {
    id: 3,
    name: "Randy Richards",
    skill: [
      { title: "AngularJs", level: 1 },
      { title: "MongoDB", level: 1 },
    ]
  },
  {
    id: 4,
    name: "Jessica Lee",
    skill: [
      { title: "AngularJs", level: 1 },
      { title: "MongoDB", level: 1 },
    ]
  },
  {
    id: 5,
    name: "Larry Sanders",
    skill: [
      { title: "AngularJs", level: 1 },
      { title: "MongoDB", level: 1 },
    ]
  },
  
]

export const Tasks = [
  {
    Task: "GSAR - Test For Accessibility Series 3",
    WorkerId: null,
    Created: "07/01/2020",
    Deadline: "08/02/2020",
    DeadlineTime: "12:42 PM",
    Points: 2000,
    Status: "Active",
    Skills: ["HTML", "CSS", "Js", "PHP","MySQL"]
  },
  {
    Task: "iOS Barcode Scanner - Scan Multiple Barcodes from WebView",
    WorkerId: 1,
    Created: "07/01/2020",
    Deadline: "08/10/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["Swift", "MongoDB","ML"]
  },
  {
    Task: "Infant Nutrition - Product scraper - Historical Data",
    WorkerId: 2,
    Created: "07/01/2020",
    Deadline: "08/11/2020",
    DeadlineTime: "12:42 PM",
    Points: 800,
    Status: "Pending",
    Skills: ["Python", "Data Science", "Linux"],
  },
  {
    Task: "CFO Forecasting - Mobile Market - Fine-Tuning Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/12/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Completed",
    Skills: ["ML", "Python", "Linux", "Data Science"],
  },
  {
    Task: "Novus Hub App PoC Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Pending",
    Skills: ["NodeJs","MongoDB", "Python", "Linux", "Data Science"]
  },
  {
    Task: "Dragonnet dRisk - ReactJS Unit Tests",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["HTML", "ReactJs", "Typescript"],
  },
  {
    Task: "CRM - Correspondence Backend API Update (WBI)",
    WorkerId: 3,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 800,
    Status: "Inactive",
    Skills: ["NodeJs", "Typescript"],
  },
  {
    Task: "Content Scraper Tool Challenge",
    WorkerId: 4,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 1000,
    Status: "Inactive",
    Skills: ["Java", ".NET", "Selenium", "Python", "NodeJs"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 3",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 4",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },

  {
    Task: "GSAR - Test For Accessibility Series 3",
    WorkerId: null,
    Created: "07/01/2020",
    Deadline: "08/02/2020",
    DeadlineTime: "12:42 PM",
    Points: 2000,
    Status: "Active",
    Skills: ["HTML", "CSS", "Js", "PHP","MySQL"]
  },
  {
    Task: "iOS Barcode Scanner - Scan Multiple Barcodes from WebView",
    WorkerId: 1,
    Created: "07/01/2020",
    Deadline: "08/10/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["Swift", "MongoDB","ML"]
  },
  {
    Task: "Infant Nutrition - Product scraper - Historical Data",
    WorkerId: 2,
    Created: "07/01/2020",
    Deadline: "08/11/2020",
    DeadlineTime: "12:42 PM",
    Points: 800,
    Status: "Pending",
    Skills: ["Python", "Data Science", "Linux"],
  },
  {
    Task: "CFO Forecasting - Mobile Market - Fine-Tuning Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/12/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Completed",
    Skills: ["ML", "Python", "Linux", "Data Science"],
  },
  {
    Task: "Novus Hub App PoC Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Pending",
    Skills: ["NodeJs","MongoDB", "Python", "Linux", "Data Science"]
  },
  {
    Task: "Dragonnet dRisk - ReactJS Unit Tests",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["HTML", "ReactJs", "Typescript"],
  },
  {
    Task: "CRM - Correspondence Backend API Update (WBI)",
    WorkerId: 3,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 800,
    Status: "Inactive",
    Skills: ["NodeJs", "Typescript"],
  },
  {
    Task: "Content Scraper Tool Challenge",
    WorkerId: 4,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 1000,
    Status: "Inactive",
    Skills: ["Java", ".NET", "Selenium", "Python", "NodeJs"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 3",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 4",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },

  {
    Task: "GSAR - Test For Accessibility Series 3",
    WorkerId: null,
    Created: "07/01/2020",
    Deadline: "08/02/2020",
    DeadlineTime: "12:42 PM",
    Points: 2000,
    Status: "Active",
    Skills: ["HTML", "CSS", "Js", "PHP","MySQL"]
  },
  {
    Task: "iOS Barcode Scanner - Scan Multiple Barcodes from WebView",
    WorkerId: 1,
    Created: "07/01/2020",
    Deadline: "08/10/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["Swift", "MongoDB","ML"]
  },
  {
    Task: "Infant Nutrition - Product scraper - Historical Data",
    WorkerId: 2,
    Created: "07/01/2020",
    Deadline: "08/11/2020",
    DeadlineTime: "12:42 PM",
    Points: 800,
    Status: "Pending",
    Skills: ["Python", "Data Science", "Linux"],
  },
  {
    Task: "CFO Forecasting - Mobile Market - Fine-Tuning Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/12/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Completed",
    Skills: ["ML", "Python", "Linux", "Data Science"],
  },
  {
    Task: "Novus Hub App PoC Challenge",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 500,
    Status: "Pending",
    Skills: ["NodeJs","MongoDB", "Python", "Linux", "Data Science"]
  },
  {
    Task: "Dragonnet dRisk - ReactJS Unit Tests",
    WorkerId: 0,
    Created: "07/01/2020",
    Deadline: "08/15/2020",
    DeadlineTime: "12:42 PM",
    Points: 1000,
    Status: "Pending",
    Skills: ["HTML", "ReactJs", "Typescript"],
  },
  {
    Task: "CRM - Correspondence Backend API Update (WBI)",
    WorkerId: 3,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 800,
    Status: "Inactive",
    Skills: ["NodeJs", "Typescript"],
  },
  {
    Task: "Content Scraper Tool Challenge",
    WorkerId: 4,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 1000,
    Status: "Inactive",
    Skills: ["Java", ".NET", "Selenium", "Python", "NodeJs"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 3",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },
  {
    Task: "Project UBahn - Swagger Specification Part 4",
    WorkerId: 5,
    Created: "07/01/2020",
    Deadline: null,
    DeadlineTime: null,
    Points: 500,
    Status: "Inactive",
    Skills: ["NodeJs", "Swagger"],
  },

]

export const Filters = {
  TasksCards : {
    RegisterdClicked: false,
    CompletedClicked: false,
    pendingClicked: false,
    failedClicked: false
  },
}